global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:

- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: node
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - docker.for.mac.localhost:9100
    labels:
      instance: 'macmini'

- job_name: unifipoller
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - unpoller:9130

- job_name: unifi-snmp
  static_configs:
    - targets:
      - 192.168.100.1
  metrics_path: /snmp
  params:
    auth: [vinechurch_v2]
    module: [if_mib]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp_exporter:9116  # The SNMP exporter's real hostname:port.

- job_name: obs-metrics-exporter
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - docker.for.mac.localhost:5555
    labels:
      instance: 'obs-metrics-exporter'