{
 "title": "OBS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up,instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Active FPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "obs_active_fps{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Total Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "obs_stream_status_output_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Encoding Skipped Frames",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "obs_output_skipped_frames{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Render Skipped Frames",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "obs_render_skipped_frames{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Skipped Frames",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "obs_stream_status_output_skipped_frames{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Skipped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "obs_stream_status_output_skipped_frames{instance=\"$instance\"} / obs_stream_status_output_total_frames{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Frames",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(obs_output_skipped_frames{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Encoding"
    },
    {
     "expr": "rate(obs_render_skipped_frames{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Render"
    },
    {
     "expr": "rate(obs_stream_status_output_skipped_frames{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Network"
    }
   ]
  },
  {
   "title": "WAN Throughput",
   "type": "timeseries",
   "description": "Spikes on this graph that are missing from the LAN graph indicate gateway-originated traffic, like a scheduled speed test. Rx is on the negative axis.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(unpoller_device_wan_receive_bytes_total{name=\"Vine\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Rx"
    },
    {
     "expr": "rate(unpoller_device_wan_transmit_bytes_total{site_name=\"Default (default)\", name=\"Vine\"}[$__interval])",
     "legendFormat": "{{name}} {{port}} Bytes Tx"
    },
    {
     "expr": "unpoller_device_wan_transmit_rate_bytes{site_name=\"Default (default)\", name=\"Vine\"}",
     "legendFormat": "{{name}} {{port}} Bytes Tx"
    },
    {
     "expr": "unpoller_device_wan_receive_rate_bytes{site_name=\"Default (default)\", name=\"Vine\"}",
     "legendFormat": "{{name}} {{port}} Bytes Rx"
    },
    {
     "expr": "rate(unpoller_device_wan_receive_bytes_total{instance=\"unpoller:9130\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(unpoller_device_wan_transmit_bytes_total{instance=\"unpoller:9130\"}[$__rate_interval])*-1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OBS Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "obs_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "obs_memory_usage{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}